src/service.c: Add tooltip support.
AyatanaIndicators/ayatana-indicator-power pull request #63
Opened 2022-07-22 13:41 UTC by sunweaver

2022-07-22 13:45 UTC, sunweaver commented
@flexiondotorg It would be nice to get your feedback on this as a English native speaker. Thanks.

2022-09-01 11:47 UTC, flexiondotorg requested changes
I would remove the (-saving) and just go with "Battery status and power management"

2022-09-01 20:26 UTC, sunweaver commented
> I would remove the (-saving) and just go with "Battery status and power management"

Done. Thx.

2022-09-01 22:00 UTC, tari01 approved these changes

2022-09-01 22:37 UTC, merged